### ISSUE TITLE
Typo error on README.md

### ISSUE THREAD

**Issue by dgarcu** [iperal2021/texmex-github#1]
Hi there!

I've seen a *typo* error related to an accent mark in the [README.md](https://github.com/iperal2021/texmex-github/blob/main/README.md) from this repo, more specifically at the **Line 5**:

#### ---
```markdown
#### Autór: Iker Peral del Pino
```
#### +++
```markdown
#### Autor: Iker Peral del Pino
```

Just a friendly ping!

**Comment by iperal2021** [comment]
Thank you¡¡
